name: Download and Use JAR

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Latest Release
        id: fetch_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/wrlannen/github_actions_1/releases/latest)
          echo "Latest release info: $latest_release"
          release_tag=$(echo $latest_release | jq -r .tag_name)
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      - name: Use Latest Release Tag
        run: |
          echo "The latest release tag is $RELEASE_TAG"
          # Perform actions with the release tag here, e.g., download assets, etc.
          

      - name: List downloaded files
        run: ls -al ~
