name: Download and Use JAR

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - uses: robinraju/release-downloader@v1
        with:
      
          # A flag to set the download target as latest release
          # The default value is 'false'
          latest: true
      
          # The name of the file to download.
          # Use this field only to specify filenames other than tarball or zipball, if any.
          # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
          fileName: demo-0.0.1-SNAPSHOT.jar
      
          # Github access token to download files from private repositories
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          # eg: token: ${{ secrets.MY_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Downloaded Asset
        run: |
          ls -l demo-0.0.1-SNAPSHOT.jar
          # Perform actions with the downloaded JAR file here
          

      - name: List downloaded files
        run: ls -al ~
